

DROP DATABASE IF EXISTS HotelReservationDB;
CREATE DATABASE HotelReservationDB;
USE HotelReservationDB;

-- Bảng 1: HOTEL
CREATE TABLE HOTEL (
    HOTEL_ID        INT AUTO_INCREMENT PRIMARY KEY,
    HOTEL_NAM       NVARCHAR(100) NOT NULL,
    ADDR            NVARCHAR(255),
   
    STAR_RATING     FLOAT CHECK (STAR_RATING >= 1 AND STAR_RATING <= 5),
    PHONE           VARCHAR(20),
    MAIL            VARCHAR(100),
    DESCRIPTION     TEXT
);

-- Bảng 2: CUSTOMER
CREATE TABLE CUSTOMER (
    CUSTOMER_ID         INT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME           NVARCHAR(100) NOT NULL,
    EMAIL               VARCHAR(100) UNIQUE,
    PHONE               VARCHAR(20),
    IDENTIFY_NUMBER     VARCHAR(50) UNIQUE -- e.g., Passport or CCCD
);


-- Bảng 3: ROOM_TYPE (Loại phòng)
-- Thực thể yếu, phụ thuộc vào HOTEL
CREATE TABLE ROOM_TYPE (
    ROOM_TYPE_ID    INT NOT NULL,
    HOTEL_ID        INT NOT NULL,
    TYPE_NAME       NVARCHAR(100) NOT NULL,
    DESCRIPTION     TEXT,
    CAPACITY        INT,
    AREA            DECIMAL(8, 2), 
    PRICE           DECIMAL(10, 2), 
    
    PRIMARY KEY (HOTEL_ID, ROOM_TYPE_ID),
    FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID)
);

-- Bảng 6: TIME_PERIOD (Khung thời gian/Giá theo mùa)
-- Phụ thuộc vào HOTEL (Mối quan hệ 1:1 'HAS_PERIOD')
CREATE TABLE TIME_PERIOD (
    TIME_PERIOD_ID  INT AUTO_INCREMENT PRIMARY KEY,
    HOTEL_ID        INT NOT NULL UNIQUE, 
    PRICE_TREND     NVARCHAR(50) 
    
    FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID)
);


-- Bảng 5: ROOM (Phòng cụ thể)

CREATE TABLE ROOM (
    HOTEL_ID        INT NOT NULL,
    ROOM_TYPE_ID    INT NOT NULL,
    ROOM_ID         INT NOT NULL, 
    ROOM_NUMBER     VARCHAR(10) NOT NULL, 
    STATUS          NVARCHAR(50), 
    
    
    PRIMARY KEY (HOTEL_ID, ROOM_TYPE_ID, ROOM_ID), 
    
  
    FOREIGN KEY (HOTEL_ID, ROOM_TYPE_ID) REFERENCES ROOM_TYPE(HOTEL_ID, ROOM_TYPE_ID)
);



-- Bảng 7: BOOKING (Đặt phòng)
-- Thực thể yếu, phụ thuộc vào CUSTOMER
CREATE TABLE BOOKING (
    CUSTOMER_ID     INT NOT NULL,
    BOOKING_ID      INT NOT NULL, 
    TIME_PERIOD_ID  INT NOT NULL,
    
    BOOKING_DATE    DATE,
    CHECK_IN_DATE   DATETIME,
    CHECK_OUT_DATE  DATETIME,
    STATUS          NVARCHAR(50), 
    
    
    PRIMARY KEY (CUSTOMER_ID, BOOKING_ID),
    
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (TIME_PERIOD_ID) REFERENCES TIME_PERIOD(TIME_PERIOD_ID)
);

-- Bảng 4: REVIEW (Đánh giá)
-- Thực thể yếu, phụ thuộc vào BOOKING
CREATE TABLE REVIEW (
    CUSTOMER_ID     INT NOT NULL, 
    BOOKING_ID      INT NOT NULL, 
    REVIEW_ID       INT NOT NULL, 
    RATING          DECIMAL(3, 1), 
    COMMENT         TEXT,
    REVIEW_DATE     DATE,
    
    )
    PRIMARY KEY (CUSTOMER_ID, BOOKING_ID, REVIEW_ID),
    
    
    FOREIGN KEY (CUSTOMER_ID, BOOKING_ID) REFERENCES BOOKING(CUSTOMER_ID, BOOKING_ID)
);

-- Bảng 8: BOOKING_ROOM (Chi tiết Phòng-Đặt phòng)
-- Bảng nối M:N giữa BOOKING và ROOM

CREATE TABLE BOOKING_ROOM (
    CUSTOMER_ID     INT NOT NULL, -- Từ PK của BOOKING
    BOOKING_ID      INT NOT NULL, -- Từ PK của BOOKING
    HOTEL_ID        INT NOT NULL, -- Từ PK của ROOM
    ROOM_TYPE_ID    INT NOT NULL, -- Từ PK của ROOM
    ROOM_ID         INT NOT NULL, -- Từ PK của ROOM
    
    -- Khóa chính 5-phần (PK của Booking + PK của Room)
    PRIMARY KEY (CUSTOMER_ID, BOOKING_ID, HOTEL_ID, ROOM_TYPE_ID, ROOM_ID),
    
    FOREIGN KEY (CUSTOMER_ID, BOOKING_ID) REFERENCES BOOKING(CUSTOMER_ID, BOOKING_ID),
    FOREIGN KEY (HOTEL_ID, ROOM_TYPE_ID, ROOM_ID) REFERENCES ROOM(HOTEL_ID, ROOM_TYPE_ID, ROOM_ID)
);

-- Bảng 9: PAYMENT (Thanh toán)
-- Phụ thuộc vào BOOKING
CREATE TABLE PAYMENT (
    PAYMENT_ID      INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID     INT NOT NULL, -- Thêm FK từ BOOKING
    BOOKING_ID      INT NOT NULL,
    PAYMENT_DATE    DATETIME,
    PAYMENT_METHOD  NVARCHAR(50), 
    AMOUNT          DECIMAL(10, 2),
    PAYMENT_STATUS  NVARCHAR(50), 
    
    FOREIGN KEY (CUSTOMER_ID, BOOKING_ID) REFERENCES BOOKING(CUSTOMER_ID, BOOKING_ID)
);


